name: 'delete-branch'
description: 'Deletes a branch from a repository'
author: 'Brendan Ingham <brendan@ingham.dev>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github_token:
    description: 'The GitHub token to use'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: true
    default: ${{ github.repository_owner }}
  repo_name:
    description: 'The name of the repository'
    required: true
    default: ${{ github.event.repository.name }}
  branch_name:
    description: 'The name of the branch to delete'
    required: true

runs:
  using: node20
  main: dist/index.js
